### ISSUE TITLE
Exception beim Serialisieren/Deserialisieren wegen Team extends TeamEntity

### ISSUE THREAD

**Issue by soggier** [NTBJass/ntb-jass#21]
Abgesehen von GameImpl, welche nicht serialisiert werden kann: Alles Messages und Entities, d.h- sämtliche Klassen, die serialisiert werden, können ausserhalb von common nicht erweitert und als Instanz der abgeleiteten Klassen verschickt werden, da die Gegenstelle die abgeleitete Klasse und deren Properties nicht kennt.

**Comment by JoaoDiogoF** [comment]
werde ich anpassen!
