### ISSUE TITLE
Player ID beim Join in die Lobby an den Client senden

### ISSUE THREAD

**Issue by soggier** [NTBJass/ntb-jass#23]
Der Server soll den Spielern, die die Lobby betreten, eine eindeutige ID zuweisen.

**Comment by JoaoDiogoF** [comment]
Spieler meldet sich mit Namen an. In der PlayerJoinedLobbyInfoMessage wird die PlayerEntity mit Datenfeld Namen und ID geschickt. Der Bot vergleicht den Namen mit seinem eigenen und übernimmt dann die ID falls diese Übereinstimmen.

PS: Es können sich keine Spieler mit dem gleichen Namen Anmelden.

**Comment by soggier** [comment]
Dann kann man sich die ID ja auch sparen, aber OK, dann ist das soweit klar.
