### ISSUE TITLE
Spielstart mit einer Message

### ISSUE THREAD

**Issue by soggier** [NTBJass/ntb-jass#24]
StartGameMessage oder boolean ChangeStateMessage.startGame, o.ä. implementieren.

Zweck: Automatisches Starten eines Spiels, sobald alle bereits anwesenden Spieler 'ready' sind.
Leere Plätze werden beim Start mit Bots gefüllt.

Sind nur Bots am Tisch, wird das Spiel unabhängig von 'startGame' automatisch gestartet (Bots sollen immer ready sein, aber 'startGame' nicht setzen).

=> Die Konfiguration des Servers mit der vorgeschlagenen Json-Datei ist aufwendiger und umständlicher in der Bedienung, da man den Server ggfs. pro spiel umkonfigurieren muss.

**Comment by JoaoDiogoF** [comment]
Spieler meldet sich mit Namen an. In der PlayerJoinedLobbyInfoMessage wird die PlayerEntity mit Datenfeld Namen und ID geschickt. Der Bot vergleicht den Namen mit seinem eigenen und übernimmt dann die ID falls diese Übereinstimmen. 

PS: Es können sich keine Spieler mit dem gleichen Namen Anmelden.

**Comment by JoaoDiogoF** [comment]
Kommentar im falschen Issue

Es gibt neu eine FillWithSlotsMessage, welche alle Freien Plätze mit Bots füllt. Das Spiel kann somit gestartet werden sobald alle Player Ready sind.
