### ISSUE TITLE
Bei Spielende die Spieler zurück in die Lobby schicken.

### ISSUE THREAD

**Issue by soggier** [NTBJass/ntb-jass#25]
Ist ein Spiel beendet oder abgebrochen, sollen die Spieler zurück in die Lobby geschickt werden.

Alternative:
* Der Tisch muss am Ende eines Spiels nicht verlassen werden, er wird ggfs. vom Client verlassen (mit LeaveTableMessage) oder beim Schliessen der Verbindung.
* JoinTableMessage zum wechseln des Sitzplatzes
* ChangeStateMessage mit dem neuen Boolean für ein neues Spiel

**Comment by JoaoDiogoF** [comment]
Alle Spieler werden vom Server aus dem Table geschmissen. Muss noch von @soggier implementiert werden. Der Bot soll darauf mit einem LeaveLobbyMessage reagieren und sich Automatisch töten.
